# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

gems:
  - jemoji
  - jekyll-paginate
  - github-pages

paginate: 5

paginate_path: "/blog/page:num/"

# Site settings
title: Riley Parsons
email: rparsons@scu.edu
description: > # this means to ignore newlines until "baseurl:"
  Riley Steele Parsons's personal website.

blog_description: > # this means to ignore newlines until "baseurl:"
  This is my blog, where I talk about things that I'm interested in.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rileyparsons.com" # the base hostname & protocol for your site
twitter_username: rileysparsons
github_username:  rileysparsons

markdown: redcarpet

logo: "/resources/images/logo.png"

cover: "/resources/images/background_image.jpg"

name: 'Riley Parsons'
author: 'Riley Parsons'
author_image: "/resources/images/Riley.jpg"


#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon: twitter
    url:  https://twitter.com/rileysparsons
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:  facebook
#    url: https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon: github
    url:  https://github.com/rileysparsons
    desc: Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:  google-plus
#    url: https://google.com/???
#    desc:  Add me on google+
#    share_url:
#    share_title:
#    share_link:

collections: 
  - projects

collections:
  projects:
    output: true

